### ISSUE TITLE
Add daemon to the build Path

### ISSUE THREAD

**Issue by jatha** [apertus-open-source-cinema/beta-software#15]
Currently, the daemon is not part of the Images. An easy way to install it would be in `build_tools/inner/update.sh`.

**Comment by jatha** [comment]
it seams like the REST API doesn't start up automatically with the axiom.service. Is this intended behavior? @BAndiT1983

**Comment by BAndiT1983** [comment]
Haven't created daemon description files for RESTServer yet. Will be done as soon as the functionality for image sensor settings is ready for real tests again. It will be a separate daemon as people asked for individual controls over this modules.
