### ISSUE TITLE
install python-numpy

### ISSUE THREAD

**Issue by sp-apertus** [apertus-open-source-cinema/beta-software#18]
install python-numpy package in the image during build process

inside this would be done with: pacman -S python-numpy

**Comment by jatha** [comment]
just add python-numpy to the `build_tools/inside/dependencies.txt` :)

**Comment by sp-apertus** [comment]
perfect :D
https://github.com/apertus-open-source-cinema/beta-software/commit/eaf69bcec83135b3edac5466e82e5712fcf48717
