### ISSUE TITLE
install lighttp

### ISSUE THREAD

**Issue by sp-apertus** [apertus-open-source-cinema/beta-software#20]
it would be great if the AXIOM Beta would have a webserver by default in the image:
https://wiki.apertus.org/index.php/Installing_a_webserver_on_AXIOM_Beta

**Comment by jatha** [comment]
Maybe this is related to #15, beacuse this needs lighthttpd installed as well (according to https://github.com/apertus-open-source-cinema/beta-software/tree/master/software/control_daemon)

**Comment by BAndiT1983** [comment]
A question for the future: Can the CI system run a minifier on webGUI JS files? Also what about e.g. LESS processor for CSS?

**Comment by davidak** [comment]
i would suggest to use nginx. it's easier to configure than apache2 (in the opinion of me and my collegues), high performance and widely used.

(i can help with configuration if needed)

**Comment by sp-apertus** [comment]
lighttp was in particular selected because the Beta has limited resources and it worked very well so far.

**Comment by jatha** [comment]
> A question for the future: Can the CI system run a minifier on webGUI JS files? Also what about e.g. LESS processor for CSS?

Yes, totally. This is completely doable, since the ci system can run arbitrary scripts. I would recommend add the minifier, you would like to use to the `build_tools/inner/dependencies.txt` and run it inside the `build_tools/inner/update.sh` :)

**Comment by jatha** [comment]
@BAndiT1983  Should we do some reverse-proxying in the Webserver to expose the API of the control-daemon under the same port as `/api/*` or something similiar?

**Comment by BAndiT1983** [comment]
Sorry for late response, was away from computer for some time. Daemon shouldn't be exposed at all to the outside, all the comms should be done through some interface like REST (see RESTServer) or similar. Only direct comm inteface daemon supports (at least at the moment) is flatbuffers and should only be used by modules available on camera (also see RESTServer for example).

**Comment by jatha** [comment]
Is https://github.com/apertus-open-source-cinema/beta-software/pull/41/files#diff-f3d735f3b1c42274f606f43a4169e60cR26 ok?

**Comment by BAndiT1983** [comment]
Looks good, just have to verify it later on my VM, as it's not really camera-dependent. WebGUI is still in progress, so the final details are still unknown but for now it's more than sufficient.
