### ISSUE TITLE
install pypng in image

### ISSUE THREAD

**Issue by sp-apertus** [apertus-open-source-cinema/beta-software#24]
This can currently be done by running
    pip install pypng

**Comment by jatha** [comment]
I think you could just add this line to the `build_tools/inside/update_inner.sh` file :)

**Comment by sp-apertus** [comment]
Will do, thanks!

**Comment by sp-apertus** [comment]
https://github.com/apertus-open-source-cinema/beta-software/commit/5b94afe6d8343a59cc7c0e0135abe0318b3cbca4
