### ISSUE TITLE
devmem missing in automatically built beta image

### ISSUE THREAD

**Issue by sp-apertus** [apertus-open-source-cinema/beta-software#34]
devmem is not installed

**Comment by jatha** [comment]
hm... wired. what was the filename of the image (which includes the commit)?

**Comment by sp-apertus** [comment]
I think I used this image: https://gitlab.com/nein/beta-software/-/jobs/39251246/artifacts/download

**Comment by jatha** [comment]
Hm... This is wired, since `devmem` is listed in `build_tools/inner/requirements.txt`.
I'll have to try to reproduce this in qemu...
