### ISSUE TITLE
Rename folder "AXIOM WebRemote" to "AXIOM-WebRemote"

### ISSUE THREAD

**Issue by nothingismagick** [apertus-open-source-cinema/beta-software#45]
Resolution with spaces in folder names is not a terrible thing, but there are build situations where it might accidentally break stuff...

change: 
https://github.com/apertus-open-source-cinema/beta-software/tree/master/software/http/AXIOM%20WebRemote

to:
https://github.com/apertus-open-source-cinema/beta-software/tree/master/software/http/AXIOM-WebRemote

**Comment by sp-apertus** [comment]
done, thanks!
