### ISSUE TITLE
bit.func is missing

### ISSUE THREAD

**Issue by jatha** [apertus-open-source-cinema/beta-software#9]
bit.func seems to be missing, which is included from `software/scripts/i2c.func`.

**Comment by jatha** [comment]
is it the same as https://github.com/apertus-open-source-cinema/alpha-hardware/blob/master/Zedboard-Files/Scripts/bit.func ?
could we just coppy it?

**Comment by sp-apertus** [comment]
added missing script: https://github.com/apertus-open-source-cinema/beta-software/commit/f070da698bc533833350520c0bacc3b56bb956d3
